name: build-verify-package
on:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'ADOPTERS*'
      - 'LICENSE'
      - 'README*'
      - 'CHANGELOG*'
      - 'ROADMAP*'
      - 'SECURITY*'
      - 'GOVERNANCE*'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'ADOPTERS*'
      - 'LICENSE'
      - 'README*'
      - 'CHANGELOG*'
      - 'ROADMAP*'
      - 'SECURITY*'
      - 'GOVERNANCE*'
permissions: read-all
jobs:
  build-verify-package:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Dependencies installation
        run: npm install

      - name: Run unit tests
        run: npm run test

      - name: Typescript compilation and Package build
        run: npm run build
